# Multi-stage starter template for:
# -Building the solution when changes to the contents of the solution folder are triggered (see trigger-SolutionName.yml for example trigger)
# -Deploying the solution to a specific environment based on pipeline variables
# This is most commonly used for PR Validation where both the build and deploy must suceeed in order for the PR checks to succeed.
steps:

- template: build-unmanaged-managed-Solution.yml

# If ImportUnmanaged variable passed in pipeline; Pass 'importUnmanaged' param to deploy-Solution.yml
- pwsh: |
    $isunmanaged = 'false'
    if('$(ImportUnmanaged)'.Contains("ImportUnmanaged")) {
        write-Host "ImportUnmanaged variable is not passed"
    }
    else {
        if('$(ImportUnmanaged)' -eq 'true'){
            Write-Host "ImportUnmanaged is passed - " $(ImportUnmanaged)
            $isunmanaged = 'true'
        }
    }

    Write-Host "##vso[task.setVariable variable=IsUnmanaged]$isunmanaged"
  displayName: "Set IsUnmanaged parameter"

- template: deploy-Solution.yml
  parameters:
    serviceConnectionName: $(ServiceConnection)
    serviceConnectionUrl: $(ServiceConnectionUrl)
    solutionName: $(SolutionName)
    environmentName: $(EnvironmentName)
    skipBuildToolsInstaller: 'true'
    importUnmanaged: $(IsUnmanaged)
