# Multi-stage starter template for:
# -Building the solution when changes to the contents of the solution folder are triggered (see trigger-SolutionName.yml for example trigger)
# -Deploying the solution to a specific environment based on pipeline variables
# This is most commonly used for PR Validation where both the build and deploy must suceeed in order for the PR checks to succeed.
parameters:
- name: pipelineDeploymentStage
  type: string
  default: "PreDeployment"
- name: sourceBranch
  type: string
  default: "NA"
- name: targetBranch
  type: string
  default: "NA"
- name: commitMessage
  type: string
  default: "NA"
- name: autoCompletePR
  type: string
  default: "false"
stages:
- stage: build_and_deploy
  displayName: 'Build and Deploy' 
  jobs:
  - job: build_and_deploy_job
    timeoutInMinutes: 0
    pool:
        vmImage: 'windows-latest'
    steps:
    - template: build-deploy-Solution-To-Environment-Common-Pipelines.yml
      parameters:
        pipelineDeploymentStage: '${{parameters.pipelineDeploymentStage}}'
        sourceBranch: '${{parameters.sourceBranch}}'
        targetBranch: '${{parameters.targetBranch}}'
        commitMessage: '${{parameters.commitMessage}}'
        autoCompletePR: '${{parameters.autoCompletePR}}'        