# Multi-stage starter template for:
# -Building the solution when changes to the contents of the solution folder are triggered (see trigger-SolutionName.yml for example trigger)
# -Deploying the solution to a specific environment based on pipeline variables
# This is most commonly used for PR Validation where both the build and deploy must suceeed in order for the PR checks to succeed.
stages:
- stage: build
  displayName: Build
  jobs:
  - job: buildjob
    pool: 
      vmImage: 'windows-2019'
    variables:
      TriggerSolutionUpgrade: 'false'
    steps:
    - template: build-Solution.yml
- stage: deploy
  displayName: Deploy
  jobs:
  - job: deployjob
    pool: 
      vmImage: 'windows-2019'
    variables:
      TriggerSolutionUpgrade: 'false'
    steps:
    - template: deploy-Solution.yml
      parameters:
        serviceConnection: '$(ServiceConnection)'
        environmentVariables: '$(EnvironmentVariables)'
        connectionReferences: '$(ConnectionReferences)'
        aadGroupTeamConfiguration: '$(AadGroupTeamConfiguration)'
        aadGroupCanvasConfiguration: '$(AadGroupCanvasConfiguration)'
        solutionComponentOwnershipConfiguration: '$(SolutionComponentOwnershipConfiguration)'
        importUnmanaged: '$(ImportUnmanaged)'