parameters:
- name: serviceConnection
  type: string

steps:
- powershell: |
   $path = "$(Pipeline.Workspace)/drop/ConfigurationMigrationData-$(EnvironmentName).zip"
   if(Test-Path $path)
   {
        Write-Host "##vso[task.setvariable variable=ConfigurationMigrationFilePath]$path"
   }
   else
   {
        $path = "$(Pipeline.Workspace)/drop/ConfigurationMigrationData.zip"
        if(Test-Path $path)
        {
            Write-Host "##vso[task.setvariable variable=ConfigurationMigrationFilePath]$path"
        }
        else
        {
            Write-Host "##vso[task.setvariable variable=ConfigurationMigrationFilePath]"
        }
   }
  displayName: 'Check if Configuration Migration Data exists'

- powershell: |
    $configurationMigrationPowerShellVersion = "1.0.0.53"
    Install-Module -Name Microsoft.Xrm.Tooling.ConfigurationMigration -RequiredVersion $configurationMigrationPowerShellVersion -Force
    Import-CrmDataFile -CrmConnection "$(CdsBaseConnectionString)${{parameters.serviceConnection}}" -Datafile "$(ConfigurationMigrationFilePath)" -Verbose
  displayName: 'Import Configuration Migration Data'
  condition: and(succeeded(), ne(variables['ConfigurationMigrationFilePath'], ''))
  #skip task if there is no ConfigurationMigrationData in the downloaded artifact