parameters:
- name: configPath
  type: string
- name: environmentName
  type: string
steps:

  #Check for deployment settings for this environment
- pwsh: |

    $settingFiles = @("deploymentSettings","customDeploymentSettings")
    $environmentName = '${{ parameters.environmentName }}'
    #Temporary workaround for naming convention mismatches. Needs to fix this issue with convention vs. configuration. This will be cleaned up via https://github.com/microsoft/coe-starter-kit/issues/1960
    if($environmentName -eq 'Validate') { $environmentName = 'Validation' }
    if($environmentName -eq 'Production') { $environmentName = 'Prod' }
    
    foreach ($settingFile in $settingFiles) {
        $deploymentSettingsPath = ''
        $path = "${{ parameters.configPath }}$settingFile-$environmentName.json"
        Write-Information "Artifact Path: $path"
        if(Test-Path $path)
        {
            $deploymentSettingsPath = $path
        }
        else
        {
            $path = "${{ parameters.configPath }}$environmentName\$settingFile.json"
            Write-Information "Environment Path: $path"
            if(Test-Path $path) {
                $deploymentSettingsPath = $path
            }
            else
            {
                $path = "${{ parameters.configPath }}$settingFile.json"
                Write-Information "Default Path: $path"
                if(Test-Path $path)
                {
                    $deploymentSettingsPath = $path
                }
            }
        }

        Write-Information "Deployment Settings Path: $deploymentSettingsPath"
        
        if($settingFile -eq "deploymentSettings")
        {
            Write-Information "##vso[task.setVariable variable=DeploymentSettingsPath]$deploymentSettingsPath"
            $useDeploymentSettings = 'false'
            if($deploymentSettingsPath -ne '') {
                $useDeploymentSettings = 'true'
            }
            Write-Information "##vso[task.setVariable variable=UseDeploymentSettings]$useDeploymentSettings"
        }
        else
        {
            Write-Information "##vso[task.setVariable variable=CustomDeploymentSettingsPath]$deploymentSettingsPath"
        }
    }
  displayName: 'Check if Deployment Settings Exist'