parameters:
- name: configPath
  type: string
- name: environmentName
  type: string
steps:

  #Check for deployment settings for this environment
- pwsh: |
    . "$env:POWERSHELLPATH/build-deploy-solution-functions.ps1"
     Check-if-Deployment-Settings-Exist '${{parameters.environmentName}}' '${{parameters.configPath}}'
  displayName: 'Check if Deployment Settings Exist'