parameters:
- name: configPath
  type: string
- name: environmentName
  type: string
- name: commitScope
  type: string
  default: '1'
steps:

  #Check for deployment settings for this environment
- pwsh: |
    . "$env:POWERSHELLPATH/build-deploy-solution-functions.ps1"
     Get-Does-Deployment-Settings-Exist '${{parameters.environmentName}}' '${{parameters.configPath}}'
  displayName: 'Check if Deployment Settings Exist'
  condition: and(succeeded(), or(eq('${{parameters.commitScope}}', '1'),eq('${{parameters.commitScope}}', '3')))