parameters:
- name: variableName
  type: string
- name: deploymentSettingsPath
  type: string
- name: deploymentSettingsNode
  type: string
- name: displayName
  type: string

steps:
- pwsh: |
    . "$env:POWERSHELLPATH/build-deploy-solution-functions.ps1"
     set-deployment-variable "${{parameters.deploymentSettingsPath}}" "${{parameters.deploymentSettingsNode}}" "${{parameters.variableName}}" "$(Agent.BuildDirectory)"
  displayName: ${{parameters.displayName}}