parameters:
- name: serviceConnection
  type: string

steps:
- powershell: |  
    $microsoftXrmDataPowerShellModule = '$(CoETools_Microsoft_Xrm_Data_PowerShell)'
    Import-Module $microsoftXrmDataPowerShellModule
    $conn = Get-CrmConnection -ConnectionString "$(CdsBaseConnectionString)${{parameters.serviceConnection}}"
    # Get the Environment name (which is a GUID)
    $environmentId = $conn.EnvironmentId 
    # Set the EnvironmentId as a global variable for use in other templates
    echo "##vso[task.setvariable variable=EnvironmentId]$environmentId"
  displayName: 'Set EnvironmentId'