parameters:
- name: orgUrl
  type: string
- name: projectName
  type: string
- name: repo
  type: string
- name: serviceConnection
  type: string
- name: solutionName
  type: string
- name: configurationData
  type: string
- name: useDeploymentSettingsPlaceholders
  type: string
  default: 'true'

steps:
- powershell: |
      # load PowerShell files into memory
      . "$env:POWERSHELLPATH/update-deployment-settings.ps1"
      Set-DeploymentSettingsConfiguration '$(Build.SourcesDirectory)' '$(Build.Repository.Name)' '$(CdsBaseConnectionString)' '$(XrmDataPowerShellVersion)' '$(CoETools_Microsoft_Xrm_Data_PowerShell)' '${{parameters.orgUrl}}' '$(System.TeamProjectId)' '${{parameters.projectName}}' '${{parameters.repo}}' 'Bearer' '${{parameters.serviceConnection}}' '${{parameters.solutionName}}' '${{parameters.useDeploymentSettingsPlaceholders}}'
  env:
    SYSTEM_ACCESSTOKEN: $(System.AccessToken)
    DEPLOYMENT_SETTINGS: ${{parameters.configurationData}}
  displayName: 'Update Deployment Settings'
  condition: succeeded()
