# variables passed in by API:
# - Project
# - Repo
# - Branch
# - SolutionName
# - ServiceConnection
# - BuildDefinitionId
# - PipelineId
# - EnvironmentName
parameters:
- name: Branch
  type: string
- name: BranchToCreate
  type: string
  default: "Commit to existing branch specified in Branch parameter"
- name: CommitMessage
  type: string
- name: Data
  type: string
  default: "[]"
- name: Email
  type: string
- name: Project
  type: string
- name: Repo
  type: string
- name: ServiceConnectionName
  type: string
- name: ServiceConnectionUrl
  type: string
- name: SolutionName
  type: string
- name: UserName
  type: string
- name: PipelineId
  type: string
  default: "NA"
- name: EnvironmentName
  type: string
  default: "NA"
- name: BuildDefinitionId
  type: string
  default: "NA"
- name: ImportUnmanaged
  type: string
  default: "true"
- name: PortalSiteName
  type: string
  default: "NA"
- name: PublishCustomizations
  type: string
  default: "NA"
- name: CommitScope
  type: string
  default: "1"
- name: AgentPool
  type: string
  default: "Azure Pipelines"
- name: VMImage
  type: string
  default: "windows-latest"
trigger: none
pr: none

variables:
- group: alm-accelerator-variable-group

name: import-${{parameters.SolutionName}}

stages:
- stage: import_unmanaged_solution
  displayName: 'Import unmanaged solution' 
  jobs:
  - job: import_unmanaged_solution
  
    pool:
      ${{ if and(ne(parameters.AgentPool, 'NA'), ne(parameters.AgentPool, '')) }}:
        name: ${{parameters.AgentPool}}
      ${{ if and(ne(parameters.VMImage, 'NA'), ne(parameters.VMImage, '')) }}:
        vmImage: ${{parameters.VMImage}}
    steps:
    - checkout: self
      path: 'PipelineUtils'
      displayName: 'Checkout Pipeline Branch'

    - template: Templates\import-Solution-To-Dev-Environment.yml
      parameters:
        branch: ${{parameters.Branch}}
        project: ${{parameters.Project}}
        repo: ${{parameters.Repo}}
        serviceConnectionName: ${{parameters.ServiceConnectionName}}
        serviceConnectionUrl: ${{parameters.ServiceConnectionUrl}}
        solutionName: ${{parameters.SolutionName}}
        environmentName: ${{parameters.EnvironmentName}}
        importUnmanaged: ${{parameters.ImportUnmanaged}}