# variables passed in by API:
# - Project
# - Repo
# - Branch
# - SolutionName
# - ServiceConnection
# - BuildDefinitionId
# - PipelineId
#
# NOTE: If you want to use different values for these variables, you can remove the variable group and attach them directly to this pipeline.

trigger: none
pr: none

variables:
- group: global-variable-group

name: import-$(SolutionName)

pool:
  vmImage: 'windows-2019'

steps:
- powershell: |
    Write-Host "##vso[task.setvariable variable=RepoName]$(Repo)"
  displayName: 'Set Source Repo Name'

- template: Templates\build-unmanaged-Solution.yml

- template: Templates\deploy-Solution.yml
  parameters:
    serviceConnection: '$(ServiceConnection)'
    environmentVariables: '$(DevEnvironmentVariables)'
    connectionReferences: '$(DevConnectionReferences)'
    aadGroupTeamConfiguration: '$(DevAadGroupTeamConfiguration)'
    aadGroupCanvasConfiguration: '$(DevAadGroupCanvasConfiguration)'
    solutionComponentOwnershipConfiguration: '$(DevSolutionComponentOwnershipConfiguration)'
    importUnmanaged: 'true'

- template: Templates\update-canvas-app-ownership.yml
  parameters:
    serviceConnection: '$(ServiceConnection)'