# This pipeline gets triggered manually or via an API call.  
# The pipeline is designed to synchronize a github repository into an Azure DevOps git repositiory.
# It facilitates:
# -Synchronization of main branch from source git repository into the Azure DevOps git repository that this pipeline is being run against

# The following variables need to be set when the pipeline is queued to run:
# Template-repo: The source github repository to be synced intot the Azure DevOps git repository that this pipeline is in.

# The following parameters are required for pipeline to run:
# BranchToCreate: The name of the new Azure DevOps Branch to create in the Repo above to which we are pulling main branch from Template-repo.

parameters:
- name: BranchToCreate
  type: string
  default: 'update-from-original-repo'
- name: CommitMessage
  type: string
  default: 'update from original repo'
  
trigger: none
pr: none

stages:
- stage: sync
  displayName: Sync
  jobs:
  - job: syncjob
    pool:
      vmImage: 'windows-2019'
    steps:
      - checkout: self
        persistCredentials: true
      
        # Configure email/name
      - script: |
          git config --global user.email "$(Build.RequestedForEmail)"
          git config --global user.name "$(Build.RequestedFor)"
        displayName: 'Set git user info'

        # Add remote and fetch main
      - script: | 
          git remote add template-repo $(TEMPLATE-REPO)
          git fetch template-repo main
        displayName: 'Fetch main branch from $(TEMPLATE-REPO)'

        # create new branch and push to origin
      - script: |
          git checkout -b ${{parameters.BranchToCreate}} template-repo/main
          git push origin +${{parameters.BranchToCreate}}
        displayName: 'Push ${{parameters.BranchToCreate}} to AzDO repo'