# This is a sample Custom Hook Template for testing hooks in the ALM Accelerator pipelines. The intention of the Custom Templates is to provide
# a library of custom hook templates that can be used by organizations in their pipelines via the hooks in their pipeline. Contributions to these 
# custom templates are welcome if you have created a hook that you believe would be useful to others.
steps:
- pwsh: |
    Get-ChildItem -Path Env:\ | Format-List
  displayName: 'Output Environment Variables'